server:
    port: 9191

spring:
  application:
    name: API-GATEWAY

#config server client properties
  config:
    import: optional:configserver:http://config-server:8888/

#  API gateway properties


  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          strip-prefix: false

      routes:
        - id: DOCTOR
          uri: lb://DOCTOR
          predicates:
            - Path=/doc/**
          filters:
            - AuthenticationFilter

        - id: MAILING-SERVICE
          uri: lb://MAILING-SERVICE
          predicates:
            - Path=/mail/**
          filters:
            - AuthenticationFilter

        - id: APPOINTMENT
          uri: lb://APPOINTMENT
          predicates:
            - Path=/apnt/**
          filters:
            - AuthenticationFilter


        - id: ADMIN
          uri: lb://ADMIN
          predicates:
            - Path=/admin/**
          filters:
            - AuthenticationFilter

        - id: PATIENT
          uri: lb://PATIENT
          predicates:
            - Path=/pat/**
          filters:
            - AuthenticationFilter

        - id: RECEPTIONIST
          uri: lb://RECEPTIONIST
          predicates:
            - Path=/rec/**
          filters:
            - AuthenticationFilter

        - id: PRESCRIPTION
          uri: lb://PRESCRIPTION
          predicates:
            - Path=/prsc/**
          filters:
            - AuthenticationFilter

        - id: ROOM
          uri: lb://ROOM
          predicates:
            - Path=/room/**
          filters:
            - AuthenticationFilter
        - id: PHARMACIST
          uri: lb://PHARMACIST
          predicates:
            - Path=/pharma/**
          filters:
            - AuthenticationFilter


        - id: GUARD
          uri: lb://GUARD
          predicates:
            - Path=/guard/**
          filters:
            - AuthenticationFilter

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "Content-Type"
              - "Authorization"
            allowCredentials: true


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true







#eureka client configuration properties shifted to git hub Access via config server
