spring:
  application:
    name: EUREKA

server:
  port: 8761

eureka:
  instance:
    hostname: localhost

  client:
    register-with-eureka: false   #will never become a client
    fetch-registry: false