# Default values for mongo-helm-chart.
# This file declares configurable parameters for Deployment, Service, and PVC.

image:
  repository: mongo
  tag: "6.0"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 27017

persistence:
  enabled: true
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  size: 1Gi

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}